---
- name: SETTING UP DEV_MYRIAD


- hosts: dev_myriad_master
  remote_user: root
  roles:
    - common
    - hadoop

- hosts: dev_myriad_master
  remote_user: hduser
  sudo: yes
  roles:
    - mesos
    - myriad
#start services

- hosts: dev_myriad_slave
  remote_user: hduser
  sudo: yes
  roles:
    - mesos
    - myriad
#start services

- hosts: dev_server_master
  remote_user: hduser
  sudo: yes
#restart services