---
- name: SETTING UP DEV_MYRIAD


- hosts: all
  remote_user: root
  roles:
    - common
    - hadoop
    - mesos    

- hosts: dev_myriad_master
  remote_user: hduser
  sudo: yes
  roles:
    - myriad

- hosts: dev_myriad_master
  remote_user: hduser
  sudo: yes
  tasks:
    - include: tasks/build.yml
    - include: tasks/start-master.yml
# transfer binary to slaves

- hosts: dev_myriad_slave
  remote_user: hduser
  sudo: yes
  tasks:
    - include: tasks/start-slave.yml