---

- name: Installing Mesos dependencies
  shell: sudo apt-get install -y autoconf libtool

- name: Installing Mesos dependencies  
  apt: name={{ item }} state=present
  with_items:
   - build-essential 
   - python-dev 
   - python-boto 
   - libcurl4-nss-dev 
   - libsasl2-dev 
   - maven 
   - libapr1-dev 
   - libsvn-dev


- name: Download mesos tar
  get_url:
    url: '{{ MESOS_INSTALL_URL }}'
    dest: "/home/{{ DEPLOY_USER }}/"

- name: Exract Mesos
  shell: tar -zxf mesos-0.25.0.tar.gz

- name: Create directory build
  shell: mkdir build
  args:
    chdir: mesos-0.25.0

- name: Run configure to create make file
  shell: ../configure >> configure-output.txt
  args:
    chdir: mesos-0.25.0/build


- name: make
  shell: make >> make-output.txt
  args:
    chdir: mesos-0.25.0/build

- name: Run test suite
  shell: make check >> make-check-output.txt
  args:
    chdir: mesos-0.25.0/build
