---

- name: Installing Mesos dependencies
  shell: sudo apt-get install -y autoconf libtool

- name: Installing Mesos dependencies  
  apt: name={{ item }} state=present
  with_items:
   - build-essential 
   - python-dev 
   - python-boto 
   - libcurl4-nss-dev 
   - libsasl2-dev 
   - maven 
   - libapr1-dev 
   - libsvn-dev


- name: Download mesos tar
  get_url:
    url: '{{ MESOS_INSTALL_URL }}'
    dest: "/home/{{ DEPLOY_USER }}/{{ MESOS_VERSION }}.tar.gz"

- name: Exract Mesos
  shell: cd /home/{{ DEPLOY_USER }}&& tar -zxf {{ MESOS_VERSION}}.tar.gz

- name: Create directory build
  file: path=/home/{{ DEPLOY_USER }}/mesos-{{ MESOS_VERSION }}/build state=directory mode=0755

- name: Run configure to create make file (see output here - build/configure-output.txt)
  shell: ../configure >> configure-output.txt
  args:
    chdir: ../../home/{{ DEPLOY_USER }}/mesos-{{ MESOS_VERSION }}/build


#- name: make (see output here - build/make-output.txt)
#  shell: make >> make-output.txt
#  args:
#    chdir: ../../home/{{ DEPLOY_USER }}/mesos-{{ MESOS_VERSION}}/build

#- name: Run test suite (see output here - build/make-check-output.txt)
#  shell: make check >> make-check-output.txt
#  args:
#    chdir: ../../home/{{ DEPLOY_USER }}/mesos-{{ MESOS_VERSION}}/build
