---

- name: update cache
  apt: update_cache=yes

- name: Installing Myriad dependencies  
  apt: name={{ item }} state=present
  with_items:
   - libcurl3
   - aria2

- name: Git clone repo mesos/myriad phase1 branch
  git: repo=git://github.com/mesos/myriad.git dest='{{ MYRIAD_HOME }}'

 
- name: Configure hadoop-env.sh
  shell: sudo sh -c 'echo export MESOS_NATIVE_JAVA_LIBRARY=/usr/local/lib/libmesos.so >> hadoop-env.sh '
  args:
    chdir: /usr/local/hadoop/etc/hadoop


- name: Configure yarn-site.xml
  lineinfile: dest=/usr/local/hadoop/etc/hadoop/yarn-site.xml 
    regexp='<configuration>' line='<configuration>
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.nodemanager.resource.cpu-vcores</name>
                                                           \\n\\t\\t<value>${nodemanager.resource.cpu-vcores}</value>
                                                           \\n\\t</property>
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.nodemanager.resource.memory-mb</name>
                                                           \\n\\t\\t<value>${nodemanager.resource.memory-mb}</value>
                                                           \\n\\t</property>
                                                           \\n<!--These options enable dynamic port assignment by mesos -->
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.nodemanager.address</name>
                                                           \\n\\t\\t<value>${myriad.yarn.nodemanager.address}</value>
                                                           \\n\\t</property>
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.nodemanager.webapp.address</name>
                                                           \\n\\t\\t<value>${myriad.yarn.nodemanager.webapp.address}</value>
                                                           \\n\\t</property>
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.nodemanager.webapp.https.address</name>
                                                           \\n\\t\\t<value>${myriad.yarn.nodemanager.webapp.address}</value>
                                                           \\n\\t</property>
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.nodemanager.localizer.address</name>
                                                           \\n\\t\\t<value>${myriad.yarn.nodemanager.localizer.address}</value>
                                                           \\n\\t</property>
                                                           \\n<!-- Configure Myriad Scheduler here -->
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>yarn.resourcemanager.scheduler.class</name>
                                                           \\n\\t\\t<value>org.apache.myriad.scheduler.yarn.MyriadFairScheduler</value>
                                                           \\n\\t</property>'
    state=present
    create=True

- name: Configure mapred-site.xml
  lineinfile: dest=/usr/local/hadoop/etc/hadoop/mapred-site.xml 
    regexp='<configuration>' line='<configuration>
                                                           \\n\\t<property>
                                                           \\n\\t\\t<name>mapreduce.shuffle.port</name>
                                                           \\n\\t\\t<value>${myriad.mapreduce.shuffle.port}\</value>
                                                           \\n\\t</property>'




